### ISSUE TITLE
2022 LFS Update

### ISSUE THREAD

**Issue by a-m-on** [mountainMath/canpumf#2]
Hello, 

Are there any planned updates to the canpumf package to accommodate website changes for the 2022 lfs data?

I get the following error when downloading 2022 data:

`> download_lfs_pumf(
+   version = "2022-01",
+   destination_dir = here("Data"))
Downloading PUMF data.
trying URL 'https://www150.statcan.gc.ca/n1/pub/71m0001x/2021001/2022-01-CSV-eng.zip'
Error in utils::download.file(path, tmp) : 
  cannot open URL 'https://www150.statcan.gc.ca/n1/pub/71m0001x/2021001/2022-01-CSV-eng.zip'
In addition: Warning message:
In utils::download.file(path, tmp) :
  cannot open URL 'https://www150.statcan.gc.ca/n1/pub/71m0001x/2021001/2022-01-CSV-eng.zip': HTTP status was '404 Not Found'`

I wonder if maybe the issue is suffix "-eng"?

Thanks!

**Comment by mountainMath** [comment]
Thanks for flagging, yes, I think the "-eng" was the issue here. I updated the package and now have (hopefully) a more robust way to get the location of the PUMF data by scraping the webpage for the correct download url. As a byproduct there is also functionality to list the available LFS PUMF data via `available_lfs_pumf_versions()`.

**Comment by a-m-on** [comment]
Thanks for updating so quickly!  And the new functionality will be helpful as well.
